apiVersion: apps/v1
kind: Deployment
metadata:
 name: normal-deployment
 labels:
   app: nginx
   normal: "yes"
   tier: "front"
spec:
 replicas: 4
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
       normal: "yes"
       tier: "front"
   spec:
     containers:
     - name: normal
       image: httpd:2.4
       ports:
       - containerPort: 80
 strategy:
   type: Recreate