apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: 266152374233.dkr.ecr.us-east-1.amazonaws.com/k8s:latest
    ports:
    - containerPort: 80
~                        