apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-lb
  name: web-lb
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: LoadBalancer
~                                                                                                                                            
~                                                                                                                                            
~                                                                                                                                            
~                             