apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver2
  name: webserver2
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    run: webserver2
  type: NodePort


~                                                                                                                                            
~                        